### ISSUE TITLE
Use `cpus` reserved name in `job.resources.scalar`

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#100]
Usage within Mesos / Marathon is consistently `cpus` and we should be consistent with that. We need to change all references to `cpu` to `cpus` within the spec.

**Comment by gisjedi** [comment]
@JohnPTobe we need to make sure we propogate this change into seed-common / seed-cli. Can we verify what impact this has and if changes are needed create appropriate linked issues?

**Comment by JohnPTobe** [comment]
just did a search on the code base and it should be just updating the tests and the example images

**Comment by JohnPTobe** [comment]
is this a dupe of #99?
