### ISSUE TITLE
Add memory and disk checks

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed#102]
Add memory and disk resource checks in test image

**Comment by gisjedi** [comment]
We need to update the files under `spec/examples/complete/` to correctly consume the environment variables as defined in the spec. For example, resource `cpus` would be injected as `ALLOCATED_CPUS` or resource `sharedMem` would be injected as `ALLOCATED_SHAREDMEM`. Reference for the injection rules can be found here: https://ngageoint.github.io/seed/master/#variable-injection
