### ISSUE TITLE
Add parameter to specify seed manifest

### ISSUE THREAD

**Issue by wong-j** [ngageoint/seed#110]
Currently must name file seed.manifest.json.  Add option to name the file something else and specify it on the command line.

**Comment by emimaesmith** [comment]
Created [#152](https://github.com/ngageoint/seed-cli/issues/152) under the Seed CLI.

**Comment by wong-j** [comment]
Doesn't appear to follow path when in subfolders, e.g.
seed build -m ./subfolder/second-seed.manifest.json
