### ISSUE TITLE
Add parameter to specify Dockerfile to use

### ISSUE THREAD

**Issue by wong-j** [ngageoint/seed#111]
Pass through the docker build -f command to name any dockerfile to build with

**Comment by emimaesmith** [comment]
Created [#151](https://github.com/ngageoint/seed-cli/issues/151) under Seed CLI.

**Comment by wong-j** [comment]
Get error:
"unable to prepare context: context must be a directory" when specifying dockerfile name.

**Comment by emimaesmith** [comment]
Doesn't actually specify the -f option - only passes through the directory for the specified Dockerifile. Re-opening to actually use the -f option to specify a specific Dockerfile.

**Comment by emimaesmith** [comment]
Re-opening [issue under Seed CLI](https://github.com/ngageoint/seed-cli/issues/151)
