### ISSUE TITLE
Chain  together build/publish command

### ISSUE THREAD

**Issue by wong-j** [ngageoint/seed#112]
Currently you need to know the image name before you can publish, however you cannot specify the image name with the seed build command.  So you can't script the build command followed by the publish command.  If I could build and publish in one step or be able to pipe or specify the image name in the build step that would allow me to script these steps.

**Comment by emimaesmith** [comment]
Created [#150](https://github.com/ngageoint/seed-cli/issues/150) under Seed CLI.
