### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#140]
**Paint Point? Please describe.**
We've got decent documentation coverage of our command line and great detail on executor implementation in the specification, but no user focused tutorial for onboarding to Seed.

**Desired Solution**
We need to build a user focused guide that contains an end-to-end tutorial and reference documentation covering common use cases that are encountered by users integrating with the system.

**Comment by mattbanderson** [comment]
Closed via [PR #233](https://github.com/ngageoint/seed-cli/pull/233) in [seed-cli](https://github.com/ngageoint/seed-cli/pull/233) repo.
