### ISSUE TITLE
CLI should identify name collisions

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#32]
Collisions between the reserved variables below and `interface.inputData.files`, `interface.inputData.json`, `interface.settings` and `resources.scalar` `name` member values MUST NOT occur. If this happens seed validation by way of CLI should fail.

Reserved Variables:
* OUTPUT_DIR

**Comment by emimaesmith** [comment]
@gisjedi Is OUTPUT_DIR the only reserved variable to check for? Were the ALLOCATED_* variables removed?
