### ISSUE TITLE
CLI: Implement search command

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#61]
We need to be able to get a list of seed compliant images from a remote registry. This will need to look for images with the `-seed` suffix. We probably want to provide 3 args for search.

```
-r registry address (default to index.docker.io)
-o org filter (default to no org filter, i.e. search across all)
-f arbitrary filter... this should support whatever syntax is consistent with registry API filtering.
```

**Comment by gisjedi** [comment]
I realized we don't have a way to retrieve images and this could be done as part of this issue. I'd propose `seed pull` or `seed get`. Pick your poison. It needs to have the same -r and -o flags as above and retag it locally without registry or org.

**Comment by JohnPTobe** [comment]
Currently there is no way to get a listing of all repositories from docker hub via the v2 api and the v2 api has no search capability.  The docker engine api has no way to list remote images. It has search but it limits results to 100 without any pagination capability.  Furthermore, the docker engine search capability strips all special characters and will return images that contain any search term.  Searching for foo-seed will return images with foo or seed in the name.  For now we will just return the 100 seed results for docker hub and come back to improving it later if possible.
