### ISSUE TITLE
Member name simplification

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#77]
I'm considering a few simplifications - namely the following:

- Rename `errorMapping` member to `errors`.
- Rename `inputData` member to `inputs`.
- Rename `outputData` member to `outputs`.

**Comment by gisjedi** [comment]
Comments, criticism? @mikenholt @dfaller @JohnPTobe @emimaesmith

**Comment by gisjedi** [comment]
I'm also considering whether we want to be more consistent in a couple other places:

- `mem` and `sharedMem` could be fully spelled out... "memory" and `sharedMemory`
- `cmd` could also be fully spelled out... it is currently in Scale Job Interface.

**Comment by mikenholt** [comment]
All 5 purposed changes seem fine to me

**Comment by JohnPTobe** [comment]
I agree with all of these changes.

**Comment by dfaller** [comment]
I agree with the first three changes, simpler is better.
I'm also fine with 'cmd' -> 'command'

I would argue against changing 'mem' as that is the exact name used by Mesos. If we use something different, any scheduling framework using Seed is going to have to translate between Seed and Mesos resources, which is an added burden and can cause name collisions/conflicts. I think we should follow the general rule that reserved/special resource names in Mesos get the identical meaning and use in Seed.

'sharedMem' is our own reserved name, but I would keep it consistent with 'mem'.

**Comment by gisjedi** [comment]
The consistency with Mesos makes sense to me. I'll address everything and leave the resources key names alone.
